buildscript {
    repositories {
        google()
        mavenCentral()
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:8.5.0'
    }
}

allprojects {
    repositories {
        google()
        mavenCentral()
        maven { url 'https://jitpack.io' }
        maven { url 'https://oss.sonatype.org/content/repositories/public/' }
        maven { url 'https://repo.jfrog.org/artifactory/libs-release/' }
        maven { url 'https://maven.pkg.github.com/ionic-team' }
    }
}

task clean(type: Delete) {
    delete rootProject.buildDir
}
